// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: rag/v1/rag.proto

package ragv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JOB_STATUS_UNSPECIFIED JobStatus = 0
	JobStatus_JOB_STATUS_PENDING     JobStatus = 1
	JobStatus_JOB_STATUS_RUNNING     JobStatus = 2
	JobStatus_JOB_STATUS_DONE        JobStatus = 3
	JobStatus_JOB_STATUS_FAILED      JobStatus = 4
	JobStatus_JOB_STATUS_CANCELLED   JobStatus = 5
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JOB_STATUS_UNSPECIFIED",
		1: "JOB_STATUS_PENDING",
		2: "JOB_STATUS_RUNNING",
		3: "JOB_STATUS_DONE",
		4: "JOB_STATUS_FAILED",
		5: "JOB_STATUS_CANCELLED",
	}
	JobStatus_value = map[string]int32{
		"JOB_STATUS_UNSPECIFIED": 0,
		"JOB_STATUS_PENDING":     1,
		"JOB_STATUS_RUNNING":     2,
		"JOB_STATUS_DONE":        3,
		"JOB_STATUS_FAILED":      4,
		"JOB_STATUS_CANCELLED":   5,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_rag_v1_rag_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_rag_v1_rag_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

// Only Go's authenticated server may produce this context.
type RequestContext struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequestId          string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	TenantId           string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId             string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AllowedShopIds     []string               `protobuf:"bytes,4,rep,name=allowed_shop_ids,json=allowedShopIds,proto3" json:"allowed_shop_ids,omitempty"`
	AllShops           bool                   `protobuf:"varint,5,opt,name=all_shops,json=allShops,proto3" json:"all_shops,omitempty"`
	PermissionRevision string                 `protobuf:"bytes,6,opt,name=permission_revision,json=permissionRevision,proto3" json:"permission_revision,omitempty"`
	ShopId             string                 `protobuf:"bytes,7,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	Role               string                 `protobuf:"bytes,8,opt,name=role,proto3" json:"role,omitempty"`
	// Signed finite scope issued by Go. An empty document list grants nothing.
	AllowedDocumentIds   []string `protobuf:"bytes,9,rep,name=allowed_document_ids,json=allowedDocumentIds,proto3" json:"allowed_document_ids,omitempty"`
	EnforceDocumentScope bool     `protobuf:"varint,10,opt,name=enforce_document_scope,json=enforceDocumentScope,proto3" json:"enforce_document_scope,omitempty"`
	ScopeSignature       string   `protobuf:"bytes,11,opt,name=scope_signature,json=scopeSignature,proto3" json:"scope_signature,omitempty"`
	ScopeExpiresAt       int64    `protobuf:"varint,12,opt,name=scope_expires_at,json=scopeExpiresAt,proto3" json:"scope_expires_at,omitempty"`
	TenantDbId           int64    `protobuf:"varint,13,opt,name=tenant_db_id,json=tenantDbId,proto3" json:"tenant_db_id,omitempty"`
	UserDbId             int64    `protobuf:"varint,14,opt,name=user_db_id,json=userDbId,proto3" json:"user_db_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RequestContext) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RequestContext) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RequestContext) GetAllowedShopIds() []string {
	if x != nil {
		return x.AllowedShopIds
	}
	return nil
}

func (x *RequestContext) GetAllShops() bool {
	if x != nil {
		return x.AllShops
	}
	return false
}

func (x *RequestContext) GetPermissionRevision() string {
	if x != nil {
		return x.PermissionRevision
	}
	return ""
}

func (x *RequestContext) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *RequestContext) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *RequestContext) GetAllowedDocumentIds() []string {
	if x != nil {
		return x.AllowedDocumentIds
	}
	return nil
}

func (x *RequestContext) GetEnforceDocumentScope() bool {
	if x != nil {
		return x.EnforceDocumentScope
	}
	return false
}

func (x *RequestContext) GetScopeSignature() string {
	if x != nil {
		return x.ScopeSignature
	}
	return ""
}

func (x *RequestContext) GetScopeExpiresAt() int64 {
	if x != nil {
		return x.ScopeExpiresAt
	}
	return 0
}

func (x *RequestContext) GetTenantDbId() int64 {
	if x != nil {
		return x.TenantDbId
	}
	return 0
}

func (x *RequestContext) GetUserDbId() int64 {
	if x != nil {
		return x.UserDbId
	}
	return 0
}

type Evidence struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	SourceType       string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceRef        string                 `protobuf:"bytes,4,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	DocumentId       string                 `protobuf:"bytes,5,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionId        string                 `protobuf:"bytes,6,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	PageNo           int32                  `protobuf:"varint,7,opt,name=page_no,json=pageNo,proto3" json:"page_no,omitempty"`
	Rank             int32                  `protobuf:"varint,8,opt,name=rank,proto3" json:"rank,omitempty"`
	RawScore         float64                `protobuf:"fixed64,9,opt,name=raw_score,json=rawScore,proto3" json:"raw_score,omitempty"`
	ShopId           string                 `protobuf:"bytes,10,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	DisclosureClass  string                 `protobuf:"bytes,11,opt,name=disclosure_class,json=disclosureClass,proto3" json:"disclosure_class,omitempty"`
	CustomerEligible bool                   `protobuf:"varint,12,opt,name=customer_eligible,json=customerEligible,proto3" json:"customer_eligible,omitempty"`
	TenantId         string                 `protobuf:"bytes,13,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Evidence) Reset() {
	*x = Evidence{}
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Evidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Evidence) ProtoMessage() {}

func (x *Evidence) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Evidence.ProtoReflect.Descriptor instead.
func (*Evidence) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{1}
}

func (x *Evidence) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Evidence) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Evidence) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *Evidence) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *Evidence) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *Evidence) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *Evidence) GetPageNo() int32 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *Evidence) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *Evidence) GetRawScore() float64 {
	if x != nil {
		return x.RawScore
	}
	return 0
}

func (x *Evidence) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *Evidence) GetDisclosureClass() string {
	if x != nil {
		return x.DisclosureClass
	}
	return ""
}

func (x *Evidence) GetCustomerEligible() bool {
	if x != nil {
		return x.CustomerEligible
	}
	return false
}

func (x *Evidence) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type Fact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ToolName      string                 `protobuf:"bytes,1,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	ObservedAt    string                 `protobuf:"bytes,3,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	IsMock        bool                   `protobuf:"varint,4,opt,name=is_mock,json=isMock,proto3" json:"is_mock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Fact) Reset() {
	*x = Fact{}
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Fact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Fact) ProtoMessage() {}

func (x *Fact) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Fact.ProtoReflect.Descriptor instead.
func (*Fact) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{2}
}

func (x *Fact) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *Fact) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

func (x *Fact) GetObservedAt() string {
	if x != nil {
		return x.ObservedAt
	}
	return ""
}

func (x *Fact) GetIsMock() bool {
	if x != nil {
		return x.IsMock
	}
	return false
}

type UnderstandRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Query          string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	HistorySummary string                 `protobuf:"bytes,3,opt,name=history_summary,json=historySummary,proto3" json:"history_summary,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UnderstandRequest) Reset() {
	*x = UnderstandRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnderstandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnderstandRequest) ProtoMessage() {}

func (x *UnderstandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnderstandRequest.ProtoReflect.Descriptor instead.
func (*UnderstandRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{3}
}

func (x *UnderstandRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UnderstandRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *UnderstandRequest) GetHistorySummary() string {
	if x != nil {
		return x.HistorySummary
	}
	return ""
}

type UnderstandResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RewrittenQuery    string                 `protobuf:"bytes,1,opt,name=rewritten_query,json=rewrittenQuery,proto3" json:"rewritten_query,omitempty"`
	Intent            string                 `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	InformationSource string                 `protobuf:"bytes,3,opt,name=information_source,json=informationSource,proto3" json:"information_source,omitempty"`
	RequiredFactTools []string               `protobuf:"bytes,4,rep,name=required_fact_tools,json=requiredFactTools,proto3" json:"required_fact_tools,omitempty"`
	Clarification     string                 `protobuf:"bytes,5,opt,name=clarification,proto3" json:"clarification,omitempty"`
	Entities          []*EntitySlot          `protobuf:"bytes,6,rep,name=entities,proto3" json:"entities,omitempty"`
	Confidence        float64                `protobuf:"fixed64,7,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Reason            string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UnderstandResponse) Reset() {
	*x = UnderstandResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnderstandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnderstandResponse) ProtoMessage() {}

func (x *UnderstandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnderstandResponse.ProtoReflect.Descriptor instead.
func (*UnderstandResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{4}
}

func (x *UnderstandResponse) GetRewrittenQuery() string {
	if x != nil {
		return x.RewrittenQuery
	}
	return ""
}

func (x *UnderstandResponse) GetIntent() string {
	if x != nil {
		return x.Intent
	}
	return ""
}

func (x *UnderstandResponse) GetInformationSource() string {
	if x != nil {
		return x.InformationSource
	}
	return ""
}

func (x *UnderstandResponse) GetRequiredFactTools() []string {
	if x != nil {
		return x.RequiredFactTools
	}
	return nil
}

func (x *UnderstandResponse) GetClarification() string {
	if x != nil {
		return x.Clarification
	}
	return ""
}

func (x *UnderstandResponse) GetEntities() []*EntitySlot {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *UnderstandResponse) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *UnderstandResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EntitySlot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Confidence    float64                `protobuf:"fixed64,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySlot) Reset() {
	*x = EntitySlot{}
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySlot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySlot) ProtoMessage() {}

func (x *EntitySlot) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySlot.ProtoReflect.Descriptor instead.
func (*EntitySlot) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{5}
}

func (x *EntitySlot) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EntitySlot) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *EntitySlot) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

type SearchRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Context             *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Query               string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	AllowExternalSearch bool                   `protobuf:"varint,3,opt,name=allow_external_search,json=allowExternalSearch,proto3" json:"allow_external_search,omitempty"`
	ResponsePurpose     string                 `protobuf:"bytes,4,opt,name=response_purpose,json=responsePurpose,proto3" json:"response_purpose,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetAllowExternalSearch() bool {
	if x != nil {
		return x.AllowExternalSearch
	}
	return false
}

func (x *SearchRequest) GetResponsePurpose() string {
	if x != nil {
		return x.ResponsePurpose
	}
	return ""
}

type SearchResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Phase          string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`
	Evidence       []*Evidence            `protobuf:"bytes,2,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Complete       bool                   `protobuf:"varint,3,opt,name=complete,proto3" json:"complete,omitempty"`
	DegradedStages []string               `protobuf:"bytes,4,rep,name=degraded_stages,json=degradedStages,proto3" json:"degraded_stages,omitempty"`
	RequestId      string                 `protobuf:"bytes,5,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	IsMock         bool                   `protobuf:"varint,6,opt,name=is_mock,json=isMock,proto3" json:"is_mock,omitempty"`
	ErrorCode      string                 `protobuf:"bytes,7,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResponse) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *SearchResponse) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *SearchResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *SearchResponse) GetDegradedStages() []string {
	if x != nil {
		return x.DegradedStages
	}
	return nil
}

func (x *SearchResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SearchResponse) GetIsMock() bool {
	if x != nil {
		return x.IsMock
	}
	return false
}

func (x *SearchResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type GenerateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Query           string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"`
	Evidence        []*Evidence            `protobuf:"bytes,3,rep,name=evidence,proto3" json:"evidence,omitempty"`
	Facts           []*Fact                `protobuf:"bytes,4,rep,name=facts,proto3" json:"facts,omitempty"`
	ResponsePurpose string                 `protobuf:"bytes,5,opt,name=response_purpose,json=responsePurpose,proto3" json:"response_purpose,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateRequest) Reset() {
	*x = GenerateRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRequest) ProtoMessage() {}

func (x *GenerateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRequest.ProtoReflect.Descriptor instead.
func (*GenerateRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{8}
}

func (x *GenerateRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *GenerateRequest) GetEvidence() []*Evidence {
	if x != nil {
		return x.Evidence
	}
	return nil
}

func (x *GenerateRequest) GetFacts() []*Fact {
	if x != nil {
		return x.Facts
	}
	return nil
}

func (x *GenerateRequest) GetResponsePurpose() string {
	if x != nil {
		return x.ResponsePurpose
	}
	return ""
}

type GenerateResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Types that are valid to be assigned to Event:
	//
	//	*GenerateResponse_Delta
	//	*GenerateResponse_Citation
	//	*GenerateResponse_UsageJson
	//	*GenerateResponse_Done
	//	*GenerateResponse_ErrorCode
	//	*GenerateResponse_IsMock
	//	*GenerateResponse_CanCopy
	Event         isGenerateResponse_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateResponse) Reset() {
	*x = GenerateResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateResponse) ProtoMessage() {}

func (x *GenerateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateResponse.ProtoReflect.Descriptor instead.
func (*GenerateResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{9}
}

func (x *GenerateResponse) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *GenerateResponse) GetEvent() isGenerateResponse_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *GenerateResponse) GetDelta() string {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_Delta); ok {
			return x.Delta
		}
	}
	return ""
}

func (x *GenerateResponse) GetCitation() *Evidence {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_Citation); ok {
			return x.Citation
		}
	}
	return nil
}

func (x *GenerateResponse) GetUsageJson() string {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_UsageJson); ok {
			return x.UsageJson
		}
	}
	return ""
}

func (x *GenerateResponse) GetDone() bool {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_Done); ok {
			return x.Done
		}
	}
	return false
}

func (x *GenerateResponse) GetErrorCode() string {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_ErrorCode); ok {
			return x.ErrorCode
		}
	}
	return ""
}

func (x *GenerateResponse) GetIsMock() bool {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_IsMock); ok {
			return x.IsMock
		}
	}
	return false
}

func (x *GenerateResponse) GetCanCopy() bool {
	if x != nil {
		if x, ok := x.Event.(*GenerateResponse_CanCopy); ok {
			return x.CanCopy
		}
	}
	return false
}

type isGenerateResponse_Event interface {
	isGenerateResponse_Event()
}

type GenerateResponse_Delta struct {
	Delta string `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type GenerateResponse_Citation struct {
	Citation *Evidence `protobuf:"bytes,3,opt,name=citation,proto3,oneof"`
}

type GenerateResponse_UsageJson struct {
	UsageJson string `protobuf:"bytes,4,opt,name=usage_json,json=usageJson,proto3,oneof"`
}

type GenerateResponse_Done struct {
	Done bool `protobuf:"varint,5,opt,name=done,proto3,oneof"`
}

type GenerateResponse_ErrorCode struct {
	ErrorCode string `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3,oneof"`
}

type GenerateResponse_IsMock struct {
	IsMock bool `protobuf:"varint,7,opt,name=is_mock,json=isMock,proto3,oneof"`
}

type GenerateResponse_CanCopy struct {
	CanCopy bool `protobuf:"varint,8,opt,name=can_copy,json=canCopy,proto3,oneof"`
}

func (*GenerateResponse_Delta) isGenerateResponse_Event() {}

func (*GenerateResponse_Citation) isGenerateResponse_Event() {}

func (*GenerateResponse_UsageJson) isGenerateResponse_Event() {}

func (*GenerateResponse_Done) isGenerateResponse_Event() {}

func (*GenerateResponse_ErrorCode) isGenerateResponse_Event() {}

func (*GenerateResponse_IsMock) isGenerateResponse_Event() {}

func (*GenerateResponse_CanCopy) isGenerateResponse_Event() {}

type ReloadSyntheticIndexRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Context            *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Chunks             []*SyntheticIndexChunk `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ReplaceDocumentIds []string               `protobuf:"bytes,3,rep,name=replace_document_ids,json=replaceDocumentIds,proto3" json:"replace_document_ids,omitempty"`
	RemoveDocumentIds  []string               `protobuf:"bytes,4,rep,name=remove_document_ids,json=removeDocumentIds,proto3" json:"remove_document_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReloadSyntheticIndexRequest) Reset() {
	*x = ReloadSyntheticIndexRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadSyntheticIndexRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSyntheticIndexRequest) ProtoMessage() {}

func (x *ReloadSyntheticIndexRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSyntheticIndexRequest.ProtoReflect.Descriptor instead.
func (*ReloadSyntheticIndexRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{10}
}

func (x *ReloadSyntheticIndexRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ReloadSyntheticIndexRequest) GetChunks() []*SyntheticIndexChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ReloadSyntheticIndexRequest) GetReplaceDocumentIds() []string {
	if x != nil {
		return x.ReplaceDocumentIds
	}
	return nil
}

func (x *ReloadSyntheticIndexRequest) GetRemoveDocumentIds() []string {
	if x != nil {
		return x.RemoveDocumentIds
	}
	return nil
}

type SyntheticIndexChunk struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId          string                 `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	DocumentId      string                 `protobuf:"bytes,3,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	VersionId       string                 `protobuf:"bytes,4,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ChunkId         string                 `protobuf:"bytes,5,opt,name=chunk_id,json=chunkId,proto3" json:"chunk_id,omitempty"`
	Title           string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	HeadingPath     string                 `protobuf:"bytes,7,opt,name=heading_path,json=headingPath,proto3" json:"heading_path,omitempty"`
	Content         string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	SourceRef       string                 `protobuf:"bytes,9,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	DisclosureClass string                 `protobuf:"bytes,10,opt,name=disclosure_class,json=disclosureClass,proto3" json:"disclosure_class,omitempty"`
	EffectiveFrom   string                 `protobuf:"bytes,11,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	EffectiveTo     string                 `protobuf:"bytes,12,opt,name=effective_to,json=effectiveTo,proto3" json:"effective_to,omitempty"`
	MetadataJson    string                 `protobuf:"bytes,13,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	SectionSeq      int32                  `protobuf:"varint,14,opt,name=section_seq,json=sectionSeq,proto3" json:"section_seq,omitempty"`
	ChunkIndex      int32                  `protobuf:"varint,15,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyntheticIndexChunk) Reset() {
	*x = SyntheticIndexChunk{}
	mi := &file_rag_v1_rag_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyntheticIndexChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyntheticIndexChunk) ProtoMessage() {}

func (x *SyntheticIndexChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyntheticIndexChunk.ProtoReflect.Descriptor instead.
func (*SyntheticIndexChunk) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{11}
}

func (x *SyntheticIndexChunk) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SyntheticIndexChunk) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *SyntheticIndexChunk) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *SyntheticIndexChunk) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *SyntheticIndexChunk) GetChunkId() string {
	if x != nil {
		return x.ChunkId
	}
	return ""
}

func (x *SyntheticIndexChunk) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SyntheticIndexChunk) GetHeadingPath() string {
	if x != nil {
		return x.HeadingPath
	}
	return ""
}

func (x *SyntheticIndexChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SyntheticIndexChunk) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *SyntheticIndexChunk) GetDisclosureClass() string {
	if x != nil {
		return x.DisclosureClass
	}
	return ""
}

func (x *SyntheticIndexChunk) GetEffectiveFrom() string {
	if x != nil {
		return x.EffectiveFrom
	}
	return ""
}

func (x *SyntheticIndexChunk) GetEffectiveTo() string {
	if x != nil {
		return x.EffectiveTo
	}
	return ""
}

func (x *SyntheticIndexChunk) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

func (x *SyntheticIndexChunk) GetSectionSeq() int32 {
	if x != nil {
		return x.SectionSeq
	}
	return 0
}

func (x *SyntheticIndexChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

type ReloadSyntheticIndexResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AcceptedChunks int32                  `protobuf:"varint,1,opt,name=accepted_chunks,json=acceptedChunks,proto3" json:"accepted_chunks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReloadSyntheticIndexResponse) Reset() {
	*x = ReloadSyntheticIndexResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadSyntheticIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadSyntheticIndexResponse) ProtoMessage() {}

func (x *ReloadSyntheticIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadSyntheticIndexResponse.ProtoReflect.Descriptor instead.
func (*ReloadSyntheticIndexResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{12}
}

func (x *ReloadSyntheticIndexResponse) GetAcceptedChunks() int32 {
	if x != nil {
		return x.AcceptedChunks
	}
	return 0
}

type SubmitRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Context         *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	SourceId        string                 `protobuf:"bytes,3,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	ObjectKey       string                 `protobuf:"bytes,4,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	PipelineVersion string                 `protobuf:"bytes,5,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SubmitRequest) Reset() {
	*x = SubmitRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitRequest) ProtoMessage() {}

func (x *SubmitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitRequest.ProtoReflect.Descriptor instead.
func (*SubmitRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{13}
}

func (x *SubmitRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SubmitRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *SubmitRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *SubmitRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *SubmitRequest) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

type SubmitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=rag.v1.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitResponse) Reset() {
	*x = SubmitResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitResponse) ProtoMessage() {}

func (x *SubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitResponse.ProtoReflect.Descriptor instead.
func (*SubmitResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{14}
}

func (x *SubmitResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SubmitResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{15}
}

func (x *GetStatusRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=rag.v1.JobStatus" json:"status,omitempty"`
	Stage         string                 `protobuf:"bytes,3,opt,name=stage,proto3" json:"stage,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{16}
}

func (x *GetStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetStatusResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

func (x *GetStatusResponse) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *GetStatusResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	JobId         string                 `protobuf:"bytes,2,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{17}
}

func (x *CancelRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *CancelRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        JobStatus              `protobuf:"varint,2,opt,name=status,proto3,enum=rag.v1.JobStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{18}
}

func (x *CancelResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *CancelResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JOB_STATUS_UNSPECIFIED
}

type PackageFile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Content       []byte                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PackageFile) Reset() {
	*x = PackageFile{}
	mi := &file_rag_v1_rag_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PackageFile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PackageFile) ProtoMessage() {}

func (x *PackageFile) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PackageFile.ProtoReflect.Descriptor instead.
func (*PackageFile) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{19}
}

func (x *PackageFile) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *PackageFile) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type ParsePackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestYaml  string                 `protobuf:"bytes,1,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	Files         []*PackageFile         `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsePackageRequest) Reset() {
	*x = ParsePackageRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsePackageRequest) ProtoMessage() {}

func (x *ParsePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsePackageRequest.ProtoReflect.Descriptor instead.
func (*ParsePackageRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{20}
}

func (x *ParsePackageRequest) GetManifestYaml() string {
	if x != nil {
		return x.ManifestYaml
	}
	return ""
}

func (x *ParsePackageRequest) GetFiles() []*PackageFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ParsePackageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ParsePackageRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type ValidatePackageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ManifestYaml  string                 `protobuf:"bytes,1,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	Files         []*PackageFile         `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	TenantId      string                 `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId        string                 `protobuf:"bytes,4,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidatePackageRequest) Reset() {
	*x = ValidatePackageRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePackageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePackageRequest) ProtoMessage() {}

func (x *ValidatePackageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePackageRequest.ProtoReflect.Descriptor instead.
func (*ValidatePackageRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{21}
}

func (x *ValidatePackageRequest) GetManifestYaml() string {
	if x != nil {
		return x.ManifestYaml
	}
	return ""
}

func (x *ValidatePackageRequest) GetFiles() []*PackageFile {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ValidatePackageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidatePackageRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

type ValidatedPackageDocument struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DocumentId      string                 `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title           string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Format          string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Path            string                 `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	SourceHash      string                 `protobuf:"bytes,5,opt,name=source_hash,json=sourceHash,proto3" json:"source_hash,omitempty"`
	DisclosureClass string                 `protobuf:"bytes,6,opt,name=disclosure_class,json=disclosureClass,proto3" json:"disclosure_class,omitempty"`
	EffectiveFrom   string                 `protobuf:"bytes,7,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	EffectiveTo     string                 `protobuf:"bytes,8,opt,name=effective_to,json=effectiveTo,proto3" json:"effective_to,omitempty"`
	VersionId       string                 `protobuf:"bytes,9,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidatedPackageDocument) Reset() {
	*x = ValidatedPackageDocument{}
	mi := &file_rag_v1_rag_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatedPackageDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatedPackageDocument) ProtoMessage() {}

func (x *ValidatedPackageDocument) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatedPackageDocument.ProtoReflect.Descriptor instead.
func (*ValidatedPackageDocument) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{22}
}

func (x *ValidatedPackageDocument) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ValidatedPackageDocument) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ValidatedPackageDocument) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ValidatedPackageDocument) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ValidatedPackageDocument) GetSourceHash() string {
	if x != nil {
		return x.SourceHash
	}
	return ""
}

func (x *ValidatedPackageDocument) GetDisclosureClass() string {
	if x != nil {
		return x.DisclosureClass
	}
	return ""
}

func (x *ValidatedPackageDocument) GetEffectiveFrom() string {
	if x != nil {
		return x.EffectiveFrom
	}
	return ""
}

func (x *ValidatedPackageDocument) GetEffectiveTo() string {
	if x != nil {
		return x.EffectiveTo
	}
	return ""
}

func (x *ValidatedPackageDocument) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type ValidatePackageResponse struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	SourceId        string                      `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName      string                      `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	PipelineVersion string                      `protobuf:"bytes,3,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	ManifestSha256  string                      `protobuf:"bytes,4,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	Documents       []*ValidatedPackageDocument `protobuf:"bytes,5,rep,name=documents,proto3" json:"documents,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ValidatePackageResponse) Reset() {
	*x = ValidatePackageResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidatePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidatePackageResponse) ProtoMessage() {}

func (x *ValidatePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidatePackageResponse.ProtoReflect.Descriptor instead.
func (*ValidatePackageResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{23}
}

func (x *ValidatePackageResponse) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ValidatePackageResponse) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ValidatePackageResponse) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

func (x *ValidatePackageResponse) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *ValidatePackageResponse) GetDocuments() []*ValidatedPackageDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

type ParsedChunk struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ChunkIndex        int32                  `protobuf:"varint,1,opt,name=chunk_index,json=chunkIndex,proto3" json:"chunk_index,omitempty"`
	SectionSeq        int32                  `protobuf:"varint,2,opt,name=section_seq,json=sectionSeq,proto3" json:"section_seq,omitempty"`
	SectionChunkIndex int32                  `protobuf:"varint,3,opt,name=section_chunk_index,json=sectionChunkIndex,proto3" json:"section_chunk_index,omitempty"`
	CharStart         int32                  `protobuf:"varint,4,opt,name=char_start,json=charStart,proto3" json:"char_start,omitempty"`
	CharEnd           int32                  `protobuf:"varint,5,opt,name=char_end,json=charEnd,proto3" json:"char_end,omitempty"`
	Title             string                 `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	HeadingPath       string                 `protobuf:"bytes,7,opt,name=heading_path,json=headingPath,proto3" json:"heading_path,omitempty"`
	Content           string                 `protobuf:"bytes,8,opt,name=content,proto3" json:"content,omitempty"`
	TokenCount        int32                  `protobuf:"varint,9,opt,name=token_count,json=tokenCount,proto3" json:"token_count,omitempty"`
	ContentType       string                 `protobuf:"bytes,10,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SplitReason       string                 `protobuf:"bytes,11,opt,name=split_reason,json=splitReason,proto3" json:"split_reason,omitempty"`
	ChunkHash         string                 `protobuf:"bytes,12,opt,name=chunk_hash,json=chunkHash,proto3" json:"chunk_hash,omitempty"`
	MetadataJson      string                 `protobuf:"bytes,13,opt,name=metadata_json,json=metadataJson,proto3" json:"metadata_json,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParsedChunk) Reset() {
	*x = ParsedChunk{}
	mi := &file_rag_v1_rag_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedChunk) ProtoMessage() {}

func (x *ParsedChunk) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedChunk.ProtoReflect.Descriptor instead.
func (*ParsedChunk) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{24}
}

func (x *ParsedChunk) GetChunkIndex() int32 {
	if x != nil {
		return x.ChunkIndex
	}
	return 0
}

func (x *ParsedChunk) GetSectionSeq() int32 {
	if x != nil {
		return x.SectionSeq
	}
	return 0
}

func (x *ParsedChunk) GetSectionChunkIndex() int32 {
	if x != nil {
		return x.SectionChunkIndex
	}
	return 0
}

func (x *ParsedChunk) GetCharStart() int32 {
	if x != nil {
		return x.CharStart
	}
	return 0
}

func (x *ParsedChunk) GetCharEnd() int32 {
	if x != nil {
		return x.CharEnd
	}
	return 0
}

func (x *ParsedChunk) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ParsedChunk) GetHeadingPath() string {
	if x != nil {
		return x.HeadingPath
	}
	return ""
}

func (x *ParsedChunk) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ParsedChunk) GetTokenCount() int32 {
	if x != nil {
		return x.TokenCount
	}
	return 0
}

func (x *ParsedChunk) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ParsedChunk) GetSplitReason() string {
	if x != nil {
		return x.SplitReason
	}
	return ""
}

func (x *ParsedChunk) GetChunkHash() string {
	if x != nil {
		return x.ChunkHash
	}
	return ""
}

func (x *ParsedChunk) GetMetadataJson() string {
	if x != nil {
		return x.MetadataJson
	}
	return ""
}

type ParsedDocument struct {
	state           protoimpl.MessageState   `protogen:"open.v1"`
	DocumentId      string                   `protobuf:"bytes,1,opt,name=document_id,json=documentId,proto3" json:"document_id,omitempty"`
	Title           string                   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Format          string                   `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	Path            string                   `protobuf:"bytes,4,opt,name=path,proto3" json:"path,omitempty"`
	SourceHash      string                   `protobuf:"bytes,5,opt,name=source_hash,json=sourceHash,proto3" json:"source_hash,omitempty"`
	DisclosureClass string                   `protobuf:"bytes,6,opt,name=disclosure_class,json=disclosureClass,proto3" json:"disclosure_class,omitempty"`
	ExternalAllowed bool                     `protobuf:"varint,7,opt,name=external_allowed,json=externalAllowed,proto3" json:"external_allowed,omitempty"`
	EffectiveFrom   string                   `protobuf:"bytes,8,opt,name=effective_from,json=effectiveFrom,proto3" json:"effective_from,omitempty"`
	EffectiveTo     string                   `protobuf:"bytes,9,opt,name=effective_to,json=effectiveTo,proto3" json:"effective_to,omitempty"`
	Chunks          []*ParsedChunk           `protobuf:"bytes,10,rep,name=chunks,proto3" json:"chunks,omitempty"`
	ArtifactBundle  *ArtifactBundleReference `protobuf:"bytes,11,opt,name=artifact_bundle,json=artifactBundle,proto3" json:"artifact_bundle,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParsedDocument) Reset() {
	*x = ParsedDocument{}
	mi := &file_rag_v1_rag_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedDocument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedDocument) ProtoMessage() {}

func (x *ParsedDocument) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedDocument.ProtoReflect.Descriptor instead.
func (*ParsedDocument) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{25}
}

func (x *ParsedDocument) GetDocumentId() string {
	if x != nil {
		return x.DocumentId
	}
	return ""
}

func (x *ParsedDocument) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ParsedDocument) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *ParsedDocument) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ParsedDocument) GetSourceHash() string {
	if x != nil {
		return x.SourceHash
	}
	return ""
}

func (x *ParsedDocument) GetDisclosureClass() string {
	if x != nil {
		return x.DisclosureClass
	}
	return ""
}

func (x *ParsedDocument) GetExternalAllowed() bool {
	if x != nil {
		return x.ExternalAllowed
	}
	return false
}

func (x *ParsedDocument) GetEffectiveFrom() string {
	if x != nil {
		return x.EffectiveFrom
	}
	return ""
}

func (x *ParsedDocument) GetEffectiveTo() string {
	if x != nil {
		return x.EffectiveTo
	}
	return ""
}

func (x *ParsedDocument) GetChunks() []*ParsedChunk {
	if x != nil {
		return x.Chunks
	}
	return nil
}

func (x *ParsedDocument) GetArtifactBundle() *ArtifactBundleReference {
	if x != nil {
		return x.ArtifactBundle
	}
	return nil
}

type ArtifactRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactType  string                 `protobuf:"bytes,1,opt,name=artifact_type,json=artifactType,proto3" json:"artifact_type,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	Sha256        string                 `protobuf:"bytes,3,opt,name=sha256,proto3" json:"sha256,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,4,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ContentType   string                 `protobuf:"bytes,5,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRecord) Reset() {
	*x = ArtifactRecord{}
	mi := &file_rag_v1_rag_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRecord) ProtoMessage() {}

func (x *ArtifactRecord) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRecord.ProtoReflect.Descriptor instead.
func (*ArtifactRecord) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{26}
}

func (x *ArtifactRecord) GetArtifactType() string {
	if x != nil {
		return x.ArtifactType
	}
	return ""
}

func (x *ArtifactRecord) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

func (x *ArtifactRecord) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *ArtifactRecord) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRecord) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type ArtifactBundleReference struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	DocumentVersionId     string                 `protobuf:"bytes,1,opt,name=document_version_id,json=documentVersionId,proto3" json:"document_version_id,omitempty"`
	ManifestObjectKey     string                 `protobuf:"bytes,2,opt,name=manifest_object_key,json=manifestObjectKey,proto3" json:"manifest_object_key,omitempty"`
	ManifestSha256        string                 `protobuf:"bytes,3,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	ArtifactSetSha256     string                 `protobuf:"bytes,4,opt,name=artifact_set_sha256,json=artifactSetSha256,proto3" json:"artifact_set_sha256,omitempty"`
	Artifacts             []*ArtifactRecord      `protobuf:"bytes,5,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	RealServiceAcceptance bool                   `protobuf:"varint,6,opt,name=real_service_acceptance,json=realServiceAcceptance,proto3" json:"real_service_acceptance,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ArtifactBundleReference) Reset() {
	*x = ArtifactBundleReference{}
	mi := &file_rag_v1_rag_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactBundleReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactBundleReference) ProtoMessage() {}

func (x *ArtifactBundleReference) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactBundleReference.ProtoReflect.Descriptor instead.
func (*ArtifactBundleReference) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{27}
}

func (x *ArtifactBundleReference) GetDocumentVersionId() string {
	if x != nil {
		return x.DocumentVersionId
	}
	return ""
}

func (x *ArtifactBundleReference) GetManifestObjectKey() string {
	if x != nil {
		return x.ManifestObjectKey
	}
	return ""
}

func (x *ArtifactBundleReference) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *ArtifactBundleReference) GetArtifactSetSha256() string {
	if x != nil {
		return x.ArtifactSetSha256
	}
	return ""
}

func (x *ArtifactBundleReference) GetArtifacts() []*ArtifactRecord {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

func (x *ArtifactBundleReference) GetRealServiceAcceptance() bool {
	if x != nil {
		return x.RealServiceAcceptance
	}
	return false
}

type ParsePackageResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SourceId        string                 `protobuf:"bytes,1,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	SourceName      string                 `protobuf:"bytes,2,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	PipelineVersion string                 `protobuf:"bytes,3,opt,name=pipeline_version,json=pipelineVersion,proto3" json:"pipeline_version,omitempty"`
	ManifestSha256  string                 `protobuf:"bytes,4,opt,name=manifest_sha256,json=manifestSha256,proto3" json:"manifest_sha256,omitempty"`
	DatasetSha256   string                 `protobuf:"bytes,5,opt,name=dataset_sha256,json=datasetSha256,proto3" json:"dataset_sha256,omitempty"`
	Documents       []*ParsedDocument      `protobuf:"bytes,6,rep,name=documents,proto3" json:"documents,omitempty"`
	ManifestYaml    string                 `protobuf:"bytes,7,opt,name=manifest_yaml,json=manifestYaml,proto3" json:"manifest_yaml,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ParsePackageResponse) Reset() {
	*x = ParsePackageResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsePackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsePackageResponse) ProtoMessage() {}

func (x *ParsePackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsePackageResponse.ProtoReflect.Descriptor instead.
func (*ParsePackageResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{28}
}

func (x *ParsePackageResponse) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *ParsePackageResponse) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *ParsePackageResponse) GetPipelineVersion() string {
	if x != nil {
		return x.PipelineVersion
	}
	return ""
}

func (x *ParsePackageResponse) GetManifestSha256() string {
	if x != nil {
		return x.ManifestSha256
	}
	return ""
}

func (x *ParsePackageResponse) GetDatasetSha256() string {
	if x != nil {
		return x.DatasetSha256
	}
	return ""
}

func (x *ParsePackageResponse) GetDocuments() []*ParsedDocument {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *ParsePackageResponse) GetManifestYaml() string {
	if x != nil {
		return x.ManifestYaml
	}
	return ""
}

type DeleteArtifactBundleRequest struct {
	state          protoimpl.MessageState   `protogen:"open.v1"`
	TenantId       string                   `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ShopId         string                   `protobuf:"bytes,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"`
	ArtifactBundle *ArtifactBundleReference `protobuf:"bytes,3,opt,name=artifact_bundle,json=artifactBundle,proto3" json:"artifact_bundle,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteArtifactBundleRequest) Reset() {
	*x = DeleteArtifactBundleRequest{}
	mi := &file_rag_v1_rag_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactBundleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactBundleRequest) ProtoMessage() {}

func (x *DeleteArtifactBundleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactBundleRequest.ProtoReflect.Descriptor instead.
func (*DeleteArtifactBundleRequest) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteArtifactBundleRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteArtifactBundleRequest) GetShopId() string {
	if x != nil {
		return x.ShopId
	}
	return ""
}

func (x *DeleteArtifactBundleRequest) GetArtifactBundle() *ArtifactBundleReference {
	if x != nil {
		return x.ArtifactBundle
	}
	return nil
}

type DeleteArtifactBundleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Complete      bool                   `protobuf:"varint,1,opt,name=complete,proto3" json:"complete,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteArtifactBundleResponse) Reset() {
	*x = DeleteArtifactBundleResponse{}
	mi := &file_rag_v1_rag_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteArtifactBundleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteArtifactBundleResponse) ProtoMessage() {}

func (x *DeleteArtifactBundleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rag_v1_rag_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteArtifactBundleResponse.ProtoReflect.Descriptor instead.
func (*DeleteArtifactBundleResponse) Descriptor() ([]byte, []int) {
	return file_rag_v1_rag_proto_rawDescGZIP(), []int{30}
}

func (x *DeleteArtifactBundleResponse) GetComplete() bool {
	if x != nil {
		return x.Complete
	}
	return false
}

func (x *DeleteArtifactBundleResponse) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

var File_rag_v1_rag_proto protoreflect.FileDescriptor

const file_rag_v1_rag_proto_rawDesc = "" +
	"\n" +
	"\x10rag/v1/rag.proto\x12\x06rag.v1\"\x85\x04\n" +
	"\x0eRequestContext\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12(\n" +
	"\x10allowed_shop_ids\x18\x04 \x03(\tR\x0eallowedShopIds\x12\x1b\n" +
	"\tall_shops\x18\x05 \x01(\bR\ballShops\x12/\n" +
	"\x13permission_revision\x18\x06 \x01(\tR\x12permissionRevision\x12\x17\n" +
	"\ashop_id\x18\a \x01(\tR\x06shopId\x12\x12\n" +
	"\x04role\x18\b \x01(\tR\x04role\x120\n" +
	"\x14allowed_document_ids\x18\t \x03(\tR\x12allowedDocumentIds\x124\n" +
	"\x16enforce_document_scope\x18\n" +
	" \x01(\bR\x14enforceDocumentScope\x12'\n" +
	"\x0fscope_signature\x18\v \x01(\tR\x0escopeSignature\x12(\n" +
	"\x10scope_expires_at\x18\f \x01(\x03R\x0escopeExpiresAt\x12 \n" +
	"\ftenant_db_id\x18\r \x01(\x03R\n" +
	"tenantDbId\x12\x1c\n" +
	"\n" +
	"user_db_id\x18\x0e \x01(\x03R\buserDbId\"\x8c\x03\n" +
	"\bEvidence\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x04 \x01(\tR\tsourceRef\x12\x1f\n" +
	"\vdocument_id\x18\x05 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x06 \x01(\tR\tversionId\x12\x17\n" +
	"\apage_no\x18\a \x01(\x05R\x06pageNo\x12\x12\n" +
	"\x04rank\x18\b \x01(\x05R\x04rank\x12\x1b\n" +
	"\traw_score\x18\t \x01(\x01R\brawScore\x12\x17\n" +
	"\ashop_id\x18\n" +
	" \x01(\tR\x06shopId\x12)\n" +
	"\x10disclosure_class\x18\v \x01(\tR\x0fdisclosureClass\x12+\n" +
	"\x11customer_eligible\x18\f \x01(\bR\x10customerEligible\x12\x1b\n" +
	"\ttenant_id\x18\r \x01(\tR\btenantId\"|\n" +
	"\x04Fact\x12\x1b\n" +
	"\ttool_name\x18\x01 \x01(\tR\btoolName\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\x12\x1f\n" +
	"\vobserved_at\x18\x03 \x01(\tR\n" +
	"observedAt\x12\x17\n" +
	"\ais_mock\x18\x04 \x01(\bR\x06isMock\"\x84\x01\n" +
	"\x11UnderstandRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12'\n" +
	"\x0fhistory_summary\x18\x03 \x01(\tR\x0ehistorySummary\"\xc2\x02\n" +
	"\x12UnderstandResponse\x12'\n" +
	"\x0frewritten_query\x18\x01 \x01(\tR\x0erewrittenQuery\x12\x16\n" +
	"\x06intent\x18\x02 \x01(\tR\x06intent\x12-\n" +
	"\x12information_source\x18\x03 \x01(\tR\x11informationSource\x12.\n" +
	"\x13required_fact_tools\x18\x04 \x03(\tR\x11requiredFactTools\x12$\n" +
	"\rclarification\x18\x05 \x01(\tR\rclarification\x12.\n" +
	"\bentities\x18\x06 \x03(\v2\x12.rag.v1.EntitySlotR\bentities\x12\x1e\n" +
	"\n" +
	"confidence\x18\a \x01(\x01R\n" +
	"confidence\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\"V\n" +
	"\n" +
	"EntitySlot\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x01R\n" +
	"confidence\"\xb6\x01\n" +
	"\rSearchRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x122\n" +
	"\x15allow_external_search\x18\x03 \x01(\bR\x13allowExternalSearch\x12)\n" +
	"\x10response_purpose\x18\x04 \x01(\tR\x0fresponsePurpose\"\xf0\x01\n" +
	"\x0eSearchResponse\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12,\n" +
	"\bevidence\x18\x02 \x03(\v2\x10.rag.v1.EvidenceR\bevidence\x12\x1a\n" +
	"\bcomplete\x18\x03 \x01(\bR\bcomplete\x12'\n" +
	"\x0fdegraded_stages\x18\x04 \x03(\tR\x0edegradedStages\x12\x1d\n" +
	"\n" +
	"request_id\x18\x05 \x01(\tR\trequestId\x12\x17\n" +
	"\ais_mock\x18\x06 \x01(\bR\x06isMock\x12\x1d\n" +
	"\n" +
	"error_code\x18\a \x01(\tR\terrorCode\"\xd6\x01\n" +
	"\x0fGenerateRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12,\n" +
	"\bevidence\x18\x03 \x03(\v2\x10.rag.v1.EvidenceR\bevidence\x12\"\n" +
	"\x05facts\x18\x04 \x03(\v2\f.rag.v1.FactR\x05facts\x12)\n" +
	"\x10response_purpose\x18\x05 \x01(\tR\x0fresponsePurpose\"\x8f\x02\n" +
	"\x10GenerateResponse\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12\x16\n" +
	"\x05delta\x18\x02 \x01(\tH\x00R\x05delta\x12.\n" +
	"\bcitation\x18\x03 \x01(\v2\x10.rag.v1.EvidenceH\x00R\bcitation\x12\x1f\n" +
	"\n" +
	"usage_json\x18\x04 \x01(\tH\x00R\tusageJson\x12\x14\n" +
	"\x04done\x18\x05 \x01(\bH\x00R\x04done\x12\x1f\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tH\x00R\terrorCode\x12\x19\n" +
	"\ais_mock\x18\a \x01(\bH\x00R\x06isMock\x12\x1b\n" +
	"\bcan_copy\x18\b \x01(\bH\x00R\acanCopyB\a\n" +
	"\x05event\"\xe6\x01\n" +
	"\x1bReloadSyntheticIndexRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x123\n" +
	"\x06chunks\x18\x02 \x03(\v2\x1b.rag.v1.SyntheticIndexChunkR\x06chunks\x120\n" +
	"\x14replace_document_ids\x18\x03 \x03(\tR\x12replaceDocumentIds\x12.\n" +
	"\x13remove_document_ids\x18\x04 \x03(\tR\x11removeDocumentIds\"\xf4\x03\n" +
	"\x13SyntheticIndexChunk\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12\x1f\n" +
	"\vdocument_id\x18\x03 \x01(\tR\n" +
	"documentId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x04 \x01(\tR\tversionId\x12\x19\n" +
	"\bchunk_id\x18\x05 \x01(\tR\achunkId\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12!\n" +
	"\fheading_path\x18\a \x01(\tR\vheadingPath\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1d\n" +
	"\n" +
	"source_ref\x18\t \x01(\tR\tsourceRef\x12)\n" +
	"\x10disclosure_class\x18\n" +
	" \x01(\tR\x0fdisclosureClass\x12%\n" +
	"\x0eeffective_from\x18\v \x01(\tR\reffectiveFrom\x12!\n" +
	"\feffective_to\x18\f \x01(\tR\veffectiveTo\x12#\n" +
	"\rmetadata_json\x18\r \x01(\tR\fmetadataJson\x12\x1f\n" +
	"\vsection_seq\x18\x0e \x01(\x05R\n" +
	"sectionSeq\x12\x1f\n" +
	"\vchunk_index\x18\x0f \x01(\x05R\n" +
	"chunkIndex\"G\n" +
	"\x1cReloadSyntheticIndexResponse\x12'\n" +
	"\x0faccepted_chunks\x18\x01 \x01(\x05R\x0eacceptedChunks\"\xd1\x01\n" +
	"\rSubmitRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12\x1b\n" +
	"\tsource_id\x18\x03 \x01(\tR\bsourceId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x04 \x01(\tR\tobjectKey\x12)\n" +
	"\x10pipeline_version\x18\x05 \x01(\tR\x0fpipelineVersion\"R\n" +
	"\x0eSubmitResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.rag.v1.JobStatusR\x06status\"[\n" +
	"\x10GetStatusRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"\x8a\x01\n" +
	"\x11GetStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.rag.v1.JobStatusR\x06status\x12\x14\n" +
	"\x05stage\x18\x03 \x01(\tR\x05stage\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\"X\n" +
	"\rCancelRequest\x120\n" +
	"\acontext\x18\x01 \x01(\v2\x16.rag.v1.RequestContextR\acontext\x12\x15\n" +
	"\x06job_id\x18\x02 \x01(\tR\x05jobId\"R\n" +
	"\x0eCancelResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12)\n" +
	"\x06status\x18\x02 \x01(\x0e2\x11.rag.v1.JobStatusR\x06status\";\n" +
	"\vPackageFile\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x18\n" +
	"\acontent\x18\x02 \x01(\fR\acontent\"\x9b\x01\n" +
	"\x13ParsePackageRequest\x12#\n" +
	"\rmanifest_yaml\x18\x01 \x01(\tR\fmanifestYaml\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.rag.v1.PackageFileR\x05files\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\tR\x06shopId\"\x9e\x01\n" +
	"\x16ValidatePackageRequest\x12#\n" +
	"\rmanifest_yaml\x18\x01 \x01(\tR\fmanifestYaml\x12)\n" +
	"\x05files\x18\x02 \x03(\v2\x13.rag.v1.PackageFileR\x05files\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x04 \x01(\tR\x06shopId\"\xb2\x02\n" +
	"\x18ValidatedPackageDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vsource_hash\x18\x05 \x01(\tR\n" +
	"sourceHash\x12)\n" +
	"\x10disclosure_class\x18\x06 \x01(\tR\x0fdisclosureClass\x12%\n" +
	"\x0eeffective_from\x18\a \x01(\tR\reffectiveFrom\x12!\n" +
	"\feffective_to\x18\b \x01(\tR\veffectiveTo\x12\x1d\n" +
	"\n" +
	"version_id\x18\t \x01(\tR\tversionId\"\xeb\x01\n" +
	"\x17ValidatePackageResponse\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12)\n" +
	"\x10pipeline_version\x18\x03 \x01(\tR\x0fpipelineVersion\x12'\n" +
	"\x0fmanifest_sha256\x18\x04 \x01(\tR\x0emanifestSha256\x12>\n" +
	"\tdocuments\x18\x05 \x03(\v2 .rag.v1.ValidatedPackageDocumentR\tdocuments\"\xb7\x03\n" +
	"\vParsedChunk\x12\x1f\n" +
	"\vchunk_index\x18\x01 \x01(\x05R\n" +
	"chunkIndex\x12\x1f\n" +
	"\vsection_seq\x18\x02 \x01(\x05R\n" +
	"sectionSeq\x12.\n" +
	"\x13section_chunk_index\x18\x03 \x01(\x05R\x11sectionChunkIndex\x12\x1d\n" +
	"\n" +
	"char_start\x18\x04 \x01(\x05R\tcharStart\x12\x19\n" +
	"\bchar_end\x18\x05 \x01(\x05R\acharEnd\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12!\n" +
	"\fheading_path\x18\a \x01(\tR\vheadingPath\x12\x18\n" +
	"\acontent\x18\b \x01(\tR\acontent\x12\x1f\n" +
	"\vtoken_count\x18\t \x01(\x05R\n" +
	"tokenCount\x12!\n" +
	"\fcontent_type\x18\n" +
	" \x01(\tR\vcontentType\x12!\n" +
	"\fsplit_reason\x18\v \x01(\tR\vsplitReason\x12\x1d\n" +
	"\n" +
	"chunk_hash\x18\f \x01(\tR\tchunkHash\x12#\n" +
	"\rmetadata_json\x18\r \x01(\tR\fmetadataJson\"\xab\x03\n" +
	"\x0eParsedDocument\x12\x1f\n" +
	"\vdocument_id\x18\x01 \x01(\tR\n" +
	"documentId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12\x12\n" +
	"\x04path\x18\x04 \x01(\tR\x04path\x12\x1f\n" +
	"\vsource_hash\x18\x05 \x01(\tR\n" +
	"sourceHash\x12)\n" +
	"\x10disclosure_class\x18\x06 \x01(\tR\x0fdisclosureClass\x12)\n" +
	"\x10external_allowed\x18\a \x01(\bR\x0fexternalAllowed\x12%\n" +
	"\x0eeffective_from\x18\b \x01(\tR\reffectiveFrom\x12!\n" +
	"\feffective_to\x18\t \x01(\tR\veffectiveTo\x12+\n" +
	"\x06chunks\x18\n" +
	" \x03(\v2\x13.rag.v1.ParsedChunkR\x06chunks\x12H\n" +
	"\x0fartifact_bundle\x18\v \x01(\v2\x1f.rag.v1.ArtifactBundleReferenceR\x0eartifactBundle\"\xae\x01\n" +
	"\x0eArtifactRecord\x12#\n" +
	"\rartifact_type\x18\x01 \x01(\tR\fartifactType\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\x12\x16\n" +
	"\x06sha256\x18\x03 \x01(\tR\x06sha256\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x04 \x01(\x03R\tsizeBytes\x12!\n" +
	"\fcontent_type\x18\x05 \x01(\tR\vcontentType\"\xc0\x02\n" +
	"\x17ArtifactBundleReference\x12.\n" +
	"\x13document_version_id\x18\x01 \x01(\tR\x11documentVersionId\x12.\n" +
	"\x13manifest_object_key\x18\x02 \x01(\tR\x11manifestObjectKey\x12'\n" +
	"\x0fmanifest_sha256\x18\x03 \x01(\tR\x0emanifestSha256\x12.\n" +
	"\x13artifact_set_sha256\x18\x04 \x01(\tR\x11artifactSetSha256\x124\n" +
	"\tartifacts\x18\x05 \x03(\v2\x16.rag.v1.ArtifactRecordR\tartifacts\x126\n" +
	"\x17real_service_acceptance\x18\x06 \x01(\bR\x15realServiceAcceptance\"\xaa\x02\n" +
	"\x14ParsePackageResponse\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1f\n" +
	"\vsource_name\x18\x02 \x01(\tR\n" +
	"sourceName\x12)\n" +
	"\x10pipeline_version\x18\x03 \x01(\tR\x0fpipelineVersion\x12'\n" +
	"\x0fmanifest_sha256\x18\x04 \x01(\tR\x0emanifestSha256\x12%\n" +
	"\x0edataset_sha256\x18\x05 \x01(\tR\rdatasetSha256\x124\n" +
	"\tdocuments\x18\x06 \x03(\v2\x16.rag.v1.ParsedDocumentR\tdocuments\x12#\n" +
	"\rmanifest_yaml\x18\a \x01(\tR\fmanifestYaml\"\x9d\x01\n" +
	"\x1bDeleteArtifactBundleRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\ashop_id\x18\x02 \x01(\tR\x06shopId\x12H\n" +
	"\x0fartifact_bundle\x18\x03 \x01(\v2\x1f.rag.v1.ArtifactBundleReferenceR\x0eartifactBundle\"Y\n" +
	"\x1cDeleteArtifactBundleResponse\x12\x1a\n" +
	"\bcomplete\x18\x01 \x01(\bR\bcomplete\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode*\x9d\x01\n" +
	"\tJobStatus\x12\x1a\n" +
	"\x16JOB_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12JOB_STATUS_PENDING\x10\x01\x12\x16\n" +
	"\x12JOB_STATUS_RUNNING\x10\x02\x12\x13\n" +
	"\x0fJOB_STATUS_DONE\x10\x03\x12\x15\n" +
	"\x11JOB_STATUS_FAILED\x10\x04\x12\x18\n" +
	"\x14JOB_STATUS_CANCELLED\x10\x052\xb0\x02\n" +
	"\n" +
	"RagService\x12C\n" +
	"\n" +
	"Understand\x12\x19.rag.v1.UnderstandRequest\x1a\x1a.rag.v1.UnderstandResponse\x129\n" +
	"\x06Search\x12\x15.rag.v1.SearchRequest\x1a\x16.rag.v1.SearchResponse0\x01\x12?\n" +
	"\bGenerate\x12\x17.rag.v1.GenerateRequest\x1a\x18.rag.v1.GenerateResponse0\x01\x12a\n" +
	"\x14ReloadSyntheticIndex\x12#.rag.v1.ReloadSyntheticIndexRequest\x1a$.rag.v1.ReloadSyntheticIndexResponse2\xc5\x03\n" +
	"\rIngestService\x127\n" +
	"\x06Submit\x12\x15.rag.v1.SubmitRequest\x1a\x16.rag.v1.SubmitResponse\x12@\n" +
	"\tGetStatus\x12\x18.rag.v1.GetStatusRequest\x1a\x19.rag.v1.GetStatusResponse\x127\n" +
	"\x06Cancel\x12\x15.rag.v1.CancelRequest\x1a\x16.rag.v1.CancelResponse\x12R\n" +
	"\x0fValidatePackage\x12\x1e.rag.v1.ValidatePackageRequest\x1a\x1f.rag.v1.ValidatePackageResponse\x12I\n" +
	"\fParsePackage\x12\x1b.rag.v1.ParsePackageRequest\x1a\x1c.rag.v1.ParsePackageResponse\x12a\n" +
	"\x14DeleteArtifactBundle\x12#.rag.v1.DeleteArtifactBundleRequest\x1a$.rag.v1.DeleteArtifactBundleResponseB=Z;github.com/ggb5023/EcommerceRAG/go/internal/pb/rag/v1;ragv1b\x06proto3"

var (
	file_rag_v1_rag_proto_rawDescOnce sync.Once
	file_rag_v1_rag_proto_rawDescData []byte
)

func file_rag_v1_rag_proto_rawDescGZIP() []byte {
	file_rag_v1_rag_proto_rawDescOnce.Do(func() {
		file_rag_v1_rag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)))
	})
	return file_rag_v1_rag_proto_rawDescData
}

var file_rag_v1_rag_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rag_v1_rag_proto_msgTypes = make([]protoimpl.MessageInfo, 31)
var file_rag_v1_rag_proto_goTypes = []any{
	(JobStatus)(0),                       // 0: rag.v1.JobStatus
	(*RequestContext)(nil),               // 1: rag.v1.RequestContext
	(*Evidence)(nil),                     // 2: rag.v1.Evidence
	(*Fact)(nil),                         // 3: rag.v1.Fact
	(*UnderstandRequest)(nil),            // 4: rag.v1.UnderstandRequest
	(*UnderstandResponse)(nil),           // 5: rag.v1.UnderstandResponse
	(*EntitySlot)(nil),                   // 6: rag.v1.EntitySlot
	(*SearchRequest)(nil),                // 7: rag.v1.SearchRequest
	(*SearchResponse)(nil),               // 8: rag.v1.SearchResponse
	(*GenerateRequest)(nil),              // 9: rag.v1.GenerateRequest
	(*GenerateResponse)(nil),             // 10: rag.v1.GenerateResponse
	(*ReloadSyntheticIndexRequest)(nil),  // 11: rag.v1.ReloadSyntheticIndexRequest
	(*SyntheticIndexChunk)(nil),          // 12: rag.v1.SyntheticIndexChunk
	(*ReloadSyntheticIndexResponse)(nil), // 13: rag.v1.ReloadSyntheticIndexResponse
	(*SubmitRequest)(nil),                // 14: rag.v1.SubmitRequest
	(*SubmitResponse)(nil),               // 15: rag.v1.SubmitResponse
	(*GetStatusRequest)(nil),             // 16: rag.v1.GetStatusRequest
	(*GetStatusResponse)(nil),            // 17: rag.v1.GetStatusResponse
	(*CancelRequest)(nil),                // 18: rag.v1.CancelRequest
	(*CancelResponse)(nil),               // 19: rag.v1.CancelResponse
	(*PackageFile)(nil),                  // 20: rag.v1.PackageFile
	(*ParsePackageRequest)(nil),          // 21: rag.v1.ParsePackageRequest
	(*ValidatePackageRequest)(nil),       // 22: rag.v1.ValidatePackageRequest
	(*ValidatedPackageDocument)(nil),     // 23: rag.v1.ValidatedPackageDocument
	(*ValidatePackageResponse)(nil),      // 24: rag.v1.ValidatePackageResponse
	(*ParsedChunk)(nil),                  // 25: rag.v1.ParsedChunk
	(*ParsedDocument)(nil),               // 26: rag.v1.ParsedDocument
	(*ArtifactRecord)(nil),               // 27: rag.v1.ArtifactRecord
	(*ArtifactBundleReference)(nil),      // 28: rag.v1.ArtifactBundleReference
	(*ParsePackageResponse)(nil),         // 29: rag.v1.ParsePackageResponse
	(*DeleteArtifactBundleRequest)(nil),  // 30: rag.v1.DeleteArtifactBundleRequest
	(*DeleteArtifactBundleResponse)(nil), // 31: rag.v1.DeleteArtifactBundleResponse
}
var file_rag_v1_rag_proto_depIdxs = []int32{
	1,  // 0: rag.v1.UnderstandRequest.context:type_name -> rag.v1.RequestContext
	6,  // 1: rag.v1.UnderstandResponse.entities:type_name -> rag.v1.EntitySlot
	1,  // 2: rag.v1.SearchRequest.context:type_name -> rag.v1.RequestContext
	2,  // 3: rag.v1.SearchResponse.evidence:type_name -> rag.v1.Evidence
	1,  // 4: rag.v1.GenerateRequest.context:type_name -> rag.v1.RequestContext
	2,  // 5: rag.v1.GenerateRequest.evidence:type_name -> rag.v1.Evidence
	3,  // 6: rag.v1.GenerateRequest.facts:type_name -> rag.v1.Fact
	2,  // 7: rag.v1.GenerateResponse.citation:type_name -> rag.v1.Evidence
	1,  // 8: rag.v1.ReloadSyntheticIndexRequest.context:type_name -> rag.v1.RequestContext
	12, // 9: rag.v1.ReloadSyntheticIndexRequest.chunks:type_name -> rag.v1.SyntheticIndexChunk
	1,  // 10: rag.v1.SubmitRequest.context:type_name -> rag.v1.RequestContext
	0,  // 11: rag.v1.SubmitResponse.status:type_name -> rag.v1.JobStatus
	1,  // 12: rag.v1.GetStatusRequest.context:type_name -> rag.v1.RequestContext
	0,  // 13: rag.v1.GetStatusResponse.status:type_name -> rag.v1.JobStatus
	1,  // 14: rag.v1.CancelRequest.context:type_name -> rag.v1.RequestContext
	0,  // 15: rag.v1.CancelResponse.status:type_name -> rag.v1.JobStatus
	20, // 16: rag.v1.ParsePackageRequest.files:type_name -> rag.v1.PackageFile
	20, // 17: rag.v1.ValidatePackageRequest.files:type_name -> rag.v1.PackageFile
	23, // 18: rag.v1.ValidatePackageResponse.documents:type_name -> rag.v1.ValidatedPackageDocument
	25, // 19: rag.v1.ParsedDocument.chunks:type_name -> rag.v1.ParsedChunk
	28, // 20: rag.v1.ParsedDocument.artifact_bundle:type_name -> rag.v1.ArtifactBundleReference
	27, // 21: rag.v1.ArtifactBundleReference.artifacts:type_name -> rag.v1.ArtifactRecord
	26, // 22: rag.v1.ParsePackageResponse.documents:type_name -> rag.v1.ParsedDocument
	28, // 23: rag.v1.DeleteArtifactBundleRequest.artifact_bundle:type_name -> rag.v1.ArtifactBundleReference
	4,  // 24: rag.v1.RagService.Understand:input_type -> rag.v1.UnderstandRequest
	7,  // 25: rag.v1.RagService.Search:input_type -> rag.v1.SearchRequest
	9,  // 26: rag.v1.RagService.Generate:input_type -> rag.v1.GenerateRequest
	11, // 27: rag.v1.RagService.ReloadSyntheticIndex:input_type -> rag.v1.ReloadSyntheticIndexRequest
	14, // 28: rag.v1.IngestService.Submit:input_type -> rag.v1.SubmitRequest
	16, // 29: rag.v1.IngestService.GetStatus:input_type -> rag.v1.GetStatusRequest
	18, // 30: rag.v1.IngestService.Cancel:input_type -> rag.v1.CancelRequest
	22, // 31: rag.v1.IngestService.ValidatePackage:input_type -> rag.v1.ValidatePackageRequest
	21, // 32: rag.v1.IngestService.ParsePackage:input_type -> rag.v1.ParsePackageRequest
	30, // 33: rag.v1.IngestService.DeleteArtifactBundle:input_type -> rag.v1.DeleteArtifactBundleRequest
	5,  // 34: rag.v1.RagService.Understand:output_type -> rag.v1.UnderstandResponse
	8,  // 35: rag.v1.RagService.Search:output_type -> rag.v1.SearchResponse
	10, // 36: rag.v1.RagService.Generate:output_type -> rag.v1.GenerateResponse
	13, // 37: rag.v1.RagService.ReloadSyntheticIndex:output_type -> rag.v1.ReloadSyntheticIndexResponse
	15, // 38: rag.v1.IngestService.Submit:output_type -> rag.v1.SubmitResponse
	17, // 39: rag.v1.IngestService.GetStatus:output_type -> rag.v1.GetStatusResponse
	19, // 40: rag.v1.IngestService.Cancel:output_type -> rag.v1.CancelResponse
	24, // 41: rag.v1.IngestService.ValidatePackage:output_type -> rag.v1.ValidatePackageResponse
	29, // 42: rag.v1.IngestService.ParsePackage:output_type -> rag.v1.ParsePackageResponse
	31, // 43: rag.v1.IngestService.DeleteArtifactBundle:output_type -> rag.v1.DeleteArtifactBundleResponse
	34, // [34:44] is the sub-list for method output_type
	24, // [24:34] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_rag_v1_rag_proto_init() }
func file_rag_v1_rag_proto_init() {
	if File_rag_v1_rag_proto != nil {
		return
	}
	file_rag_v1_rag_proto_msgTypes[9].OneofWrappers = []any{
		(*GenerateResponse_Delta)(nil),
		(*GenerateResponse_Citation)(nil),
		(*GenerateResponse_UsageJson)(nil),
		(*GenerateResponse_Done)(nil),
		(*GenerateResponse_ErrorCode)(nil),
		(*GenerateResponse_IsMock)(nil),
		(*GenerateResponse_CanCopy)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rag_v1_rag_proto_rawDesc), len(file_rag_v1_rag_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   31,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_rag_v1_rag_proto_goTypes,
		DependencyIndexes: file_rag_v1_rag_proto_depIdxs,
		EnumInfos:         file_rag_v1_rag_proto_enumTypes,
		MessageInfos:      file_rag_v1_rag_proto_msgTypes,
	}.Build()
	File_rag_v1_rag_proto = out.File
	file_rag_v1_rag_proto_goTypes = nil
	file_rag_v1_rag_proto_depIdxs = nil
}
