# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from rag.v1 import rag_pb2 as rag_dot_v1_dot_rag__pb2


class RagServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Understand = channel.unary_unary(
                '/rag.v1.RagService/Understand',
                request_serializer=rag_dot_v1_dot_rag__pb2.UnderstandRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.UnderstandResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_stream(
                '/rag.v1.RagService/Search',
                request_serializer=rag_dot_v1_dot_rag__pb2.SearchRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_stream(
                '/rag.v1.RagService/Generate',
                request_serializer=rag_dot_v1_dot_rag__pb2.GenerateRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.ReloadSyntheticIndex = channel.unary_unary(
                '/rag.v1.RagService/ReloadSyntheticIndex',
                request_serializer=rag_dot_v1_dot_rag__pb2.ReloadSyntheticIndexRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.ReloadSyntheticIndexResponse.FromString,
                _registered_method=True)


class RagServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Understand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadSyntheticIndex(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RagServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Understand': grpc.unary_unary_rpc_method_handler(
                    servicer.Understand,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.UnderstandRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.UnderstandResponse.SerializeToString,
            ),
            'Search': grpc.unary_stream_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.SearchRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.SearchResponse.SerializeToString,
            ),
            'Generate': grpc.unary_stream_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.GenerateRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.GenerateResponse.SerializeToString,
            ),
            'ReloadSyntheticIndex': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadSyntheticIndex,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.ReloadSyntheticIndexRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.ReloadSyntheticIndexResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.RagService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.RagService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RagService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Understand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagService/Understand',
            rag_dot_v1_dot_rag__pb2.UnderstandRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.UnderstandResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.RagService/Search',
            rag_dot_v1_dot_rag__pb2.SearchRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/rag.v1.RagService/Generate',
            rag_dot_v1_dot_rag__pb2.GenerateRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadSyntheticIndex(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.RagService/ReloadSyntheticIndex',
            rag_dot_v1_dot_rag__pb2.ReloadSyntheticIndexRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.ReloadSyntheticIndexResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class IngestServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Submit = channel.unary_unary(
                '/rag.v1.IngestService/Submit',
                request_serializer=rag_dot_v1_dot_rag__pb2.SubmitRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.SubmitResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/rag.v1.IngestService/GetStatus',
                request_serializer=rag_dot_v1_dot_rag__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.Cancel = channel.unary_unary(
                '/rag.v1.IngestService/Cancel',
                request_serializer=rag_dot_v1_dot_rag__pb2.CancelRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.CancelResponse.FromString,
                _registered_method=True)
        self.ValidatePackage = channel.unary_unary(
                '/rag.v1.IngestService/ValidatePackage',
                request_serializer=rag_dot_v1_dot_rag__pb2.ValidatePackageRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.ValidatePackageResponse.FromString,
                _registered_method=True)
        self.ParsePackage = channel.unary_unary(
                '/rag.v1.IngestService/ParsePackage',
                request_serializer=rag_dot_v1_dot_rag__pb2.ParsePackageRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.ParsePackageResponse.FromString,
                _registered_method=True)
        self.DeleteArtifactBundle = channel.unary_unary(
                '/rag.v1.IngestService/DeleteArtifactBundle',
                request_serializer=rag_dot_v1_dot_rag__pb2.DeleteArtifactBundleRequest.SerializeToString,
                response_deserializer=rag_dot_v1_dot_rag__pb2.DeleteArtifactBundleResponse.FromString,
                _registered_method=True)


class IngestServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Submit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Cancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidatePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ParsePackage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteArtifactBundle(self, request, context):
        """Internal synthetic-ingest cleanup after a database transaction rolls back.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Submit': grpc.unary_unary_rpc_method_handler(
                    servicer.Submit,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.SubmitRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.SubmitResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.GetStatusRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.GetStatusResponse.SerializeToString,
            ),
            'Cancel': grpc.unary_unary_rpc_method_handler(
                    servicer.Cancel,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.CancelRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.CancelResponse.SerializeToString,
            ),
            'ValidatePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidatePackage,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.ValidatePackageRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.ValidatePackageResponse.SerializeToString,
            ),
            'ParsePackage': grpc.unary_unary_rpc_method_handler(
                    servicer.ParsePackage,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.ParsePackageRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.ParsePackageResponse.SerializeToString,
            ),
            'DeleteArtifactBundle': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteArtifactBundle,
                    request_deserializer=rag_dot_v1_dot_rag__pb2.DeleteArtifactBundleRequest.FromString,
                    response_serializer=rag_dot_v1_dot_rag__pb2.DeleteArtifactBundleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rag.v1.IngestService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rag.v1.IngestService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IngestService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Submit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.IngestService/Submit',
            rag_dot_v1_dot_rag__pb2.SubmitRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.SubmitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.IngestService/GetStatus',
            rag_dot_v1_dot_rag__pb2.GetStatusRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Cancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.IngestService/Cancel',
            rag_dot_v1_dot_rag__pb2.CancelRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.CancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidatePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.IngestService/ValidatePackage',
            rag_dot_v1_dot_rag__pb2.ValidatePackageRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.ValidatePackageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ParsePackage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.IngestService/ParsePackage',
            rag_dot_v1_dot_rag__pb2.ParsePackageRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.ParsePackageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteArtifactBundle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rag.v1.IngestService/DeleteArtifactBundle',
            rag_dot_v1_dot_rag__pb2.DeleteArtifactBundleRequest.SerializeToString,
            rag_dot_v1_dot_rag__pb2.DeleteArtifactBundleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
